# Generated by Django 3.2.9 on 2021-11-16 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='upvote',
            field=models.ManyToManyField(null=True, related_name='blog_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
