# Generated by Django 3.2.9 on 2021-11-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211118_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
