# Generated by Django 3.2.9 on 2021-11-18 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_blogpost_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='comments',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comments',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='core.comment'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='upvote',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='upvote',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_liked', to='account.user'),
            preserve_default=False,
        ),
    ]
