# Generated by Django 3.2.9 on 2021-11-18 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20211118_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='comments',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='post_comments', to='core.Comment'),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='upvote',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='blog_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
